"""Add tagline column to entity table.

Short disambiguating summary for each entity (e.g., "british prog rock band").
Generated by the LLM during entity identification and used in search queries.
"""

import sqlite3


def up(conn: sqlite3.Connection) -> None:
    """Apply the migration."""
    cursor = conn.cursor()
    columns = [row[1] for row in cursor.execute("PRAGMA table_info(entity)").fetchall()]
    if "tagline" not in columns:
        cursor.execute("ALTER TABLE entity ADD COLUMN tagline TEXT")
    conn.commit()
